# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 02 Mar 2008 13:31:18 +0000
*	@ALL	1
*	@phpcvs	16
*	@user	1
doc	@doc	2
doc:*	@doc	8
internals:references	barelon	2
internals:windows	@wintendo	2
internals:windows:*	@wintendo	8
licenses:*	@ALL	0
licenses:*	@phpcvs	16
oauth:*	@ALL	0
oauth:*	@phpcvs	16
pear:*	@pear	8
phpng-upgrading	@php7upgrading	2
rfc	@rfc	2
rfc:*	@rfc	8
systems	@systems	2
todo:*	@todo	8
usergroups	@usergroups	2
usergroups:*	@usergroups	8
vcs:*	@vcs	8
web:*	@web	8
