# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 02 Mar 2008 13:31:18 +0000
*               @ALL          1
*	@phpcvs	16
*	@user	1
rfc:*	@rfc	8
todo:*	@todo	8
web:*	@web	8
pear:*	@pear	8

