<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: bjori
 * Date: Mon, 16 Dec 2013 17:50:08 +0000
 */

$conf['title'] = 'PHP Wiki';
$conf['template'] = 'phpnet';
$conf['fmode'] = 0777;
$conf['useacl'] = 1;
$conf['authtype'] = 'phpcvs';
$conf['superuser'] = '@admin';
$conf['manager'] = '@phpcvs';
$conf['disableactions'] = 'profile';
$conf['subscribers'] = 1;
$conf['registernotify'] = 'webmaster@php.net';
$conf['mailfrom'] = 'php-webmaster@lists.php.net';
$conf['htmlmail'] = 0;
$conf['rss_content'] = 'htmldiff';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['send404'] = 1;

// end auto-generated content
